### ISSUE TITLE
OnePiece.Commanded.Event with JsonbSerializer and events evolution

### ISSUE THREAD

**Issue by vheathen** [straw-hat-team/beam-monorepo#143]
### Problem Statement

Sorry for bringing it up here, I tried to find OnePiece.Commanded-related discussions on ElixirForum but didn't find any, and this is quite specific one, so I decided to give a shot here.

I'm trying to use OnePiece.Commanded to my new project and evaluating an option to use its `JsonbSerializer`. It expects to have all events built agains the `Event` module or at least have a `new!/1` function. 

As I understand, the idea of the `ObjectValue` sitting underneath the `Event` is to use `Ecto` to deserialize supported types into a runtime event struct, and this is totally legit and sound.

The question is what scenario you think would be the best in the feature when it is necessary to evolve events? 

### Solution Brainstorm

I'm not a big fan of keeping old structures just to support legacy, it brings a lot of confusion and mistakes during development, especially when a team is big enough. With the `Upcaster` protocol implementation it is possible to update some event's fields to the new shape or even build a completely new current **_runtime_** event representation. But if we keep only the current shape of the event structure it would break casting: either silently when some fields just don't get their way into a pre-upcasted structure or loudly, when fields just can't be casted anymore. The original Commanded `JsonDecoder` protocol gives the power to cast specific values to the event-specific implementation. But if we enforce casting right after reading an event from the event store - it won't work. And yes, it is possible to redefine the `new!/1` method to do things there, but then it replaces the `Upcaster` protocol in many ways and requires using internal `ValueObject` implementation functions to continue casting.

I understand that it is possible to just continue to use the original scenario with Commanded JsonDecoder, but I would kindly ask to share your thoughts on the topic if you don't mind.

**Comment by yordis** [comment]
Can you share the precise up-casting you would like to perform? So, we set the proper context, which narrows down the decision-making.

Sometimes, it is a matter of documenting a different perspective.

---

> Sorry for bringing it up here; I tried to find OnePiece.Commanded-related discussions on ElixirForum but didn't find any, and this is quite specific one, so I decided to give a shot here.

I am not active in ElixirForum and barely check there. You could bring the problem here!

---

I think it is worth sharing the intent of why it was left out; I am not saying I am right, nor am I opposed to changing it, to be extra precise.

I believe "the past can never change." This implies that you must handle the past as is, with no breaking changes ever.
Up-casting practices "mask" the past, and I found that it is much more troublesome sometimes than not.


In practice, if we mess up badly, we cut a v2 stream because of such an unreliable stream and remove the problems altogether. That does not mean we changed the past, but we agree that moving forward, we should not do anything about that past or ignore it.

> I'm not a big fan of keeping old structures just to support legacy,

I think this is where we disagree. My intent was that you never remove such Events. You could ignore them, but you must keep them around and Up-Cast to whatever you want. But, at the very least, your code shows the past. It does not hide it behind transformation that "does require" understanding the past anyway. So even if you remove such old structure, it is still there, just that it is even more confusing, hidden behind runtime code that can not be statically analyzed. More problems than keeping them data structures around.

---

>  evaluating an option to use its JsonbSerializer.

Side note: I can take an implementation to be JSON and `bytes`; there is no reason not to do that either!

**Comment by vheathen** [comment]
Thanks for the answer!

> Side note: I can take an implementation to be JSON and bytes; there is no reason not to do that either!

I believe that `jsonb` is the best option for now. Sometimes it is necessary to work with raw data when debugging or doing one-time investigation of something, and `jsonb` allows to make queries and get indexes to do it faster. The `bytea` and `term_to_binary` has one huge downside which we recently hit: the resulting binary can change in the future versions. It`s not a big problem for events as long as it is possible to decode them to the same structure, but still a bit risky: compatibility guaranteed for two OTP major versions only.

> I believe "the past can never change." This implies that you must handle the past as is, with no breaking changes ever.
Up-casting practices "mask" the past, and I found that it is much more troublesome sometimes than not.

I agree with the idea that "the past never changes" and it doesn't (I mean, you can't go back and change a fact), but I think that events are not "the past", it's just a model, a perception or a projection of what happened. And with time we can realize that our perception was incomplete or incorrect. And thus, we don't change the representation we had before, but from some point we should start to work with a new representation. It is inevitable: things are changing, in the real life as well.

For example, we realized that it is not enough to register a date only, we need a timestamp. We would change the field type in the event schema, I believe nobody would create a new event with all the fields for that.

Another a bit less simple example: we had an address as a string, but then our business process changed, and now to better represent it we need a structure with separated country, zip, city and street. From now on the runtime will issue the new events with an address as a struct. But what to do with the old ones? We can't request all consumers to support both versions, it would be a nightmare.

I thought about a solution quite much, all options have cons, there is no the ideal one exists, but I found that adding an `__event_version__` field to the event struct is a good trade-off: we don't clutter the code with `Event`, `EventV1`, `EventV2` etc (from my experience: someone will definitely use the wrong version if it is possible to choose from, or forget to update to the newest one if the old one is still in the system; but changing types in the current version would break tests, so it is much more noticeable). I wrote a simple wrapper which is using the `TypedStruct` underneath, got a guard and a version alter function to hide implementation, and now it is possible to define an event like this:

```elixir
defmodule SomeEvent do
   use EventStruct

  event_struct enforce: true do
    field :user_id, String.t()
    field :address, String.t()
  end
end
```

this will add an additional field to the struct with the default value 1.

Then when you need to evolve the event you can just change the default version and define the Upcaster implementation:

```elixir
defmodule SomeEvent do
   use EventStruct

  event_struct enforce: true, version: 2 do
    field :user_id, String.t()
    field :address, map()
  end
end

defimpl Commanded.Event.Upcaster, for: SomeEvent do
  import EventStruct, only: [increment_version: 1, version: 1]

  def upcast(%SomeEvent{} = event, _metadata) when version(event) == 1 do
    %{event | address: tranfsorm_address_to_struct(event.address)}
    |> increment_version()
  end

  def upcast(event, _metadata), do: event

  defp tranfsorm_address_to_struct(address) when is_string(address), do: %{}
end
```

The main downside is that now we get a field inside each event which has only technical meaning. But that's fine for me: it clearly shows the evolution of the event. And this approach delegates all responsibility to build the correct current representation of an event to the event module itself. `Commanded.Serialization.JsonDecoder` is also delegates that responsibility to the event module and the event-specific implementation of the protocol.

Currently my team is using a custom serializer, which works quite well with some precaution, but I don't like that approach, it keeps implementation details inside events themselves (like struct names etc). As any module renaming will hurt in this case (unless mapping is specified in the deserializer itself) we decided to reduce usage of external structures to the bare minimum, but anyway, it doesn't scale well in the long run from my point of view. So, I'm trying to find another solution for my pet project, and if it works - to bring it to the bigger production scale.

I thought a lot about using Ecto casting to deserialize events, but exactly the problem I started with stops me from that. So, I'm trying to find a solution.

A side note too: anyway, I'm starting a new pet project with OnePiece.Commanded primitives (with the only addition is that I also made a similar `VerionedEctoSchema` module to add the version field and automatically generate types for the schema itself) and will see where it brings me. As all of that are the runtime things, it is easy to change implementation later. Maybe I will try to use `PolymorphicEctoEmbed` lib, but this would require external modules and I'm not sure it would work all together.

**Comment by yordis** [comment]
@vheathen any updates about your experience? I would love to learn from it if possible

**Comment by vheathen** [comment]
@yordis Sorry, somehow, I missed the previous message.

I can't tell much for now. I haven't got a chance to evolve events, but I found a way to do that if necessary while keeping only last schemas. It isn't completely pretty, but at least gives a chance to do the trick.

Also, I introduced `OnePiece.Commanded` to my team, and they are actually quite happy about some conceptions in it. So, I can thank you for this library again, this time from them :)

**Comment by yordis** [comment]
@vheathen btw, related to the topic https://youtu.be/W7mpfjW7nhw?si=cSEbhYO2leYygs4k&t=2491 timestamp: 41:31

**Comment by vheathen** [comment]
@yordis 

I've looked at the upcaster part of that episode, thank you, very interesting!

I can't tell I completely agree though.

I believe that there is more than the only one "right" way to do things. We are developers, and we use approaches which suit better for the purpose. The only part actually "carved in stone" is our events, we should not change them, and we don't change them [until there is really no other way to do that, but this is another topic]. The runtime code is flexible, in theory we can ditch all of it and rewrite in a different language, with different approach if necessary. We have our history in the event streams containing original events, inside the event store.

And we always have trade-offs. 

One place to deal with changes or multiple places? We need to remember that every new projection would need to support all history of these similar events. Do we actually need all of the changes in all subscribers? If not, and if we just use a new version of the same event, in most cases we don't even need to modify projections which don't need those changes (let's think about registration of a new user and a projection which needs only name/email, for example, and don't care about any other info like birth date or address or eye color).

Does the event change its meaning or just gets additional information we didn't think we need before (either because of bad design or new requirements/business process updates)?

Do we get a new field (or multiple), or we need to modify an existing one (birth date vs address representation)?

And, at the end, how do we name those new events in case the meaning is the same? Do we add "version" suffix to the new events?

One of the most important things from my point of view: do we think it worth to add additional cognitive load to the developers? Sometimes it's really hard to understand which events are actual, and which are not. Keeping only actual event versions runtime can reduce that load much, I can tell that from my own experience.

But my main idea is to use tools the most suitable for the task. So, in some cases this would be adding a new event along with the current one, in other cases it can be event upcasting.
